pragma Singleton
import QtQuick

// GENERATED by tools/tablet/starlite-theme-previews -- do not edit.
// Each entry is what wallust produced for that theme, so swatches preview the real
// colours and mock mode has a full palette without wallust installed.
QtObject {
    readonly property var list: [
        { id: "ariadne", label: "Ariadne", cmd: ["wallust", "cs", "/home/adamrel/.config/wallust/colorschemes/ariadne.json"], bg: "#0B100E", fg: "#E9F2EF", accent: "#14B88F", critical: "#E5534B", success: "#3FB950" },
        { id: "nord", label: "Nord", cmd: ["wallust", "theme", "Nord"], bg: "#2E3440", fg: "#D8DEE9", accent: "#81A1C1", critical: "#BF616A", success: "#A3BE8C" },
        { id: "nord-light", label: "Nord Light", cmd: ["wallust", "theme", "Nord-Light"], bg: "#EBEAF2", fg: "#004F7C", accent: "#439ECF", critical: "#E64569", success: "#069F5F" },
        { id: "gruvbox", label: "Gruvbox", cmd: ["wallust", "theme", "Gruvbox-Dark"], bg: "#282828", fg: "#EBDBB2", accent: "#458588", critical: "#CC241D", success: "#98971A" },
        { id: "gruvbox-light", label: "Gruvbox Light", cmd: ["wallust", "theme", "Gruvbox-Material-Light"], bg: "#FBF1C7", fg: "#654735", accent: "#45707A", critical: "#C14A4A", success: "#6C782E" },
        { id: "tokyo-night", label: "Tokyo Night", cmd: ["wallust", "theme", "Tokyo-Night"], bg: "#1A1B26", fg: "#C0CAF5", accent: "#7AA2F7", critical: "#F7768E", success: "#9ECE6A" },
        { id: "tokyo-light", label: "Tokyo Light", cmd: ["wallust", "theme", "Tokyo-Night-Light"], bg: "#D5D6DB", fg: "#565A6E", accent: "#34548A", critical: "#8C4351", success: "#485E30" },
        { id: "catppuccin", label: "Catppuccin", cmd: ["wallust", "theme", "Catppuccin-Mocha"], bg: "#1E1E2E", fg: "#CDD6F4", accent: "#89B4FA", critical: "#F38BA8", success: "#A6E3A1" },
        { id: "latte", label: "Latte", cmd: ["wallust", "theme", "Catppuccin-Latte"], bg: "#EFF1F5", fg: "#4C4F69", accent: "#1E66F5", critical: "#D20F39", success: "#40A02B" },
        { id: "dracula", label: "Dracula", cmd: ["wallust", "theme", "Dracula"], bg: "#282A36", fg: "#F8F8F2", accent: "#9B6BDF", critical: "#E64747", success: "#42E66C" },
        { id: "everforest", label: "Everforest", cmd: ["wallust", "theme", "Everforest-Dark-Medium"], bg: "#2D353B", fg: "#D3C6AA", accent: "#7FBBB3", critical: "#E67E80", success: "#A7C080" },
        { id: "everforest-light", label: "Everforest Light", cmd: ["wallust", "theme", "Everforest-Light-Medium"], bg: "#FDF6E3", fg: "#5C6A72", accent: "#3A94C5", critical: "#F85552", success: "#8DA101" },
        { id: "kanagawa", label: "Kanagawa", cmd: ["wallust", "theme", "Kanagawa-Wave"], bg: "#1F1F28", fg: "#DCD7BA", accent: "#7E9CD8", critical: "#C34043", success: "#76946A" },
        { id: "lotus", label: "Lotus", cmd: ["wallust", "theme", "Kanagawa-Lotus"], bg: "#F2ECBC", fg: "#545464", accent: "#4D699B", critical: "#C84053", success: "#6F894E" },
        { id: "one-dark", label: "One Dark", cmd: ["wallust", "theme", "One-Dark"], bg: "#1E2127", fg: "#5C6370", accent: "#61AFEF", critical: "#E06C75", success: "#98C379" },
        { id: "solarized", label: "Solarized", cmd: ["wallust", "theme", "Solarized-Dark"], bg: "#002B36", fg: "#839496", accent: "#268BD2", critical: "#DC322F", success: "#859900" },
        { id: "solarized-light", label: "Solarized Light", cmd: ["wallust", "theme", "Solarized-Light"], bg: "#FDF6E3", fg: "#657B83", accent: "#268BD2", critical: "#DC322F", success: "#859900" },
        { id: "oxocarbon", label: "Oxocarbon", cmd: ["wallust", "theme", "Oxocarbon-Dark"], bg: "#161616", fg: "#FFFFFF", accent: "#33B1FF", critical: "#EE5396", success: "#42BE65" },
        { id: "paper", label: "Paper", cmd: ["wallust", "theme", "Paper"], bg: "#F2EEDE", fg: "#000000", accent: "#1E6FCC", critical: "#CC3E28", success: "#216609" }
    ]
}
